version: "3"

services:
  app:
    build: .
    container_name: app
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
    depends_on:
      - db
    restart: always
    volumes:
      - .:/var/www
    networks:
      - app-network

  nginx:
    build: ./.docker/nginx
    entrypoint: dockerize -template ./.docker/nginx/nginx.tmpl:/etc/nginx/conf.d/nginx.conf ./.docker/nginx/entrypoint.sh
    depends_on:
      - app
    container_name: nginx
    restart: always
    environment:
      - APP_HOST=app
      - APP_PORT=80
      - APP_FPM=9000
    tty: true
    ports:
      - "80:80"
    volumes:
      - .:/var/www
    networks:
      - app-network

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - app-network
    healthcheck:
      test: ['CMD-SHELL', 'mysql -uroot --database=laravel --password=root --execute="SELECT count(table_name) > 0 FROM information_schema.tables;" --skip-column-names -B']
      interval: 10s
      timeout: 10s
      retries: 4

  redis:
    image: redis:alpine
    container_name: redis
    expose:
      - 6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
